namespace: "vidimensional"
name: "github_release_lookup"
description: Lookup release information for a given GitHub repository.
version: "0.0.1"
readme: "README.md"
authors:
  - "Daniel Vidal de la Rubia (https://github.com/vidimensional)"
license:
  - "WTFPL"
tags:
  - github
  - releases
  - lookup
repository: "https://github.com/Vidimensional/ansible_github_releases_lookup"
