name: Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: ansible_collections/${{ github.repository }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then 
            pip install -r requirements.txt
          fi
        working-directory: ansible_collections/${{ github.repository }}

      - name: Run Ansible sanity checks
        run: ansible-test sanity -v --docker --redact --python 3.10 --color yes
        working-directory: ansible_collections/${{ github.repository }}

      - name: Run unit tests
        run: python -m unittest discover -s ./test/unit/
        working-directory: ansible_collections/${{ github.repository }}
