name: Publish to Ansible Galaxy

on:
  push:
    tags:
      - "*"

jobs:
  RunTests:
    uses: vidimensional/ansible_github_releases_lookup/.github/workflows/tests.yaml@main

  PublishToAnsibleGalaxy:
    needs: RunTests
    uses: vidimensional/ansible_github_releases_lookup/.github/workflows/publish.yaml@main
    secrets:
      ANSIBLE_GALAXY_API_KEY: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
